### ISSUE TITLE
Nutzeraktualisierung schlägt fehl

### ISSUE THREAD

**Issue by blumenk0hl** [benjaminraabe/wrs-patientendoku#4]
Guten Abend,

folgendes Problem ist gegeben:

Sobald ich einen Benutzer (den Standard-Admin-Benutzer) deaktivieren möchte, erhalte ich einen Fehler 500, die Änderungen werden nicht übernommen.

Erwartetes Verhalten:

Ich aktualisiere den Nutzer, die Datenänderung wird ausgeführt und die Webseite gibt keinen HTML-Response 500 zurück.

Logeintrag:

Zu dem geschilderten Problem gibt es folgenden Logeintrag im Log der Webserverinstanz:

`[Sun Jul 21 02:39:22.500355 2024] [proxy_fcgi:error] [pid xxx] [client xxx] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `wrsdoku`.`USER`.`ACTIVE` at row 1 in /var/www/wrsbhp/backend/utils.php:47\nStack trace:\n#0 /var/www/wrsbhp/backend/utils.php(47): PDOStatement->execute()\n#1 /var/www/wrsbhp/backend/process_admin_page.php(155): safeExecute()\n#2 {main}\n  thrown in /var/www/wrsbhp/backend/utils.php on line 47', referer: https://bhp.drk-kaltenkirchen.de/frontend/adminpage.php`

**Comment by benjaminraabe** [comment]
Behoben. Vielen Dank für Meldung und Bugfix!
